Add feature: MultiCheckbox (checkboxes with multiple choices).
givebutter/laravel-custom-fields pull request #42
Opened 2024-02-25 23:12 UTC by RenoLooijmans

2024-03-05 19:42 UTC, ClintWinter requested changes
Thanks for this! We have an internal version of this that I just haven't gotten around to adding back into the package.

If you wouldn't mind making a few tweaks I'm happy to merge this.

2024-03-05 19:42 UTC, ClintWinter commented on config/custom-fields.php
> +        'multicheckbox' => \Givebutter\LaravelCustomFields\FieldTypes\MultiCheckboxFieldType::class,
Rename "multicheckbox" to "multiselect". Checkbox is overly-specific and the input doesn't always have to be a checkbox. (i.e. `<select multiple>`)

2024-03-05 19:42 UTC, ClintWinter commented on src/FieldTypes/MultiCheckboxFieldType.php
> +            ]),
The `required` rule implies that there will be at least 1 value, so you can drop the `min:1` ternary and the `array_filter` wrapper.

2024-03-05 19:42 UTC, ClintWinter commented on src/FieldTypes/MultiCheckboxFieldType.php
> +                Rule::in($this->field->answers),
Let's also add `distinct` here just to make sure there are no duplicates.

2024-03-05 19:42 UTC, ClintWinter commented on src/ResponseTypes/MultiCheckboxResponseType.php
> +    }
Can drop this as it doesn't modify the behavior of the parent class.

2024-03-05 19:42 UTC, ClintWinter commented on src/ResponseTypes/MultiCheckboxResponseType.php
> +    }
Can drop this too. I think it's overly cautious to not trust the data in our DB to not be an array as that's the format we require in the validation.

2024-03-05 19:42 UTC, ClintWinter commented on src/ResponseTypes/MultiCheckboxResponseType.php
> +        return implode(', ', $list);
I think all we need is a guard clause for `null` because as I said above it'll either be an array or `null`. We also shouldn't need to check `isset` on the available answers. Try this:

```php
if (is_null($this->getValue())) {
    return '';
}

return Arr::join($this->getValue(), ', ');
```

2024-04-08 03:21 UTC, RenoLooijmans commented
Hi Clint, thanks for your reply and sorry for my late answer. I'm happy to make these changes, though I'm interested in your internal version as well. If it's better I don't see why my pull request should be added back into the package :-)

I'm on holiday the next weeks, but I'll be sure to make these adjustments when I am back. Thanks again.

2024-04-09 15:23 UTC, ClintWinter commented
The versions are very close other than the few comments I left, so I was trying to be nice and allow you to make a successful contribution rather than undercut you. 

If you don't care, we can add the internal version instead, but you may end up making the adjustments before that happens 😆

Whichever comes first!

2025-04-28 00:35 UTC, closed without merging